[project]
name = "pracstremlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.3",
    "pydantic>=2.9.2",
    "sqlalchemy>=2.0.36",
    "streamlit>=1.39.0",
    "uvicorn>=0.32.0",
]
